### ISSUE TITLE
QPN BIDS subjects without pheno info

### ISSUE THREAD

**Issue by surchs** [neurodatascience/mr_proc-qpn#8]
Hi,

I found two subjects with BIDS data, but no entry in the phenotypic bagel.csv file.

bids path on bic: `/data/pd/qpn/bids`
bagel.csv path on bic: `/data/pd/qpn/tabular/bagel.csv`

These are the subjects:

`'sub-PD00339', 'sub-PD00955', 'sub-PD00122', 'sub-PD01746', 'sub-MNI0136', 'sub-PD01744',
'sub-PD01626', 'sub-PD00953', 'sub-PD01199', 'sub-PD01715', 'sub-PD01709', 'sub-PD01713', 'sub-MNI0079', 'sub-PD01003', 'sub-PD01737', 'sub-PD01551', 'sub-PD00952', 'sub-MNI0200'`

@nikhil153

**Comment by nikhil153** [comment]
@surchs - hmm this is odd. These must have existed in the QPN manifest list at some point and then got removed for some reason. Let me check with the recruitment people and get back.

**Comment by nikhil153** [comment]
Checked with @alyssadai - the newly baked QPN bagel no longer has subjects with missing phenotypic data.
